### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by lucarin91** [di-unipi-socc/tosKer#1]
- [x] Controllare la definizione del tipo “Container”, derivandolo da tipo TOSCA, e “volume”
- [x] Gestire anche relazioni diverse da hosting (e.g., connessione ad un database) e link
- [ ] Gestire anche CSAR in input
- [x] _Controllare se è possibile integrare il Di Tommaso parser_ (probabilmente non vale la pena per ora)
